{{/*
Expand the name of the chart.
*/}}
{{- define "cloudapp.name" -}}
{{- default .Chart.Name | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "cloudapp.labels" -}}
{{ include "cloudapp.selectorLabels" . }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "cloudapp.selectorLabels" -}}
k8s-app: {{ include "cloudapp.name" . }}
qcloud-app: {{ include "cloudapp.name" . }}
{{- end }}

{{/*
Image Pull Secret
*/}}
{{- define "imagePullSecret" }}
{{- with .Values.cloudappImageCredentials }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}